### ISSUE TITLE
about evaluate 

### ISSUE THREAD

**Issue by 4359hhh** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#10]
there are two datesets ,bbox_test and query ,in /baseline/evaluate.py,but i don't konw how to create ,could you teel me ,thanks .

**Comment by 4359hhh** [comment]
CUHK03

**Comment by hehefan** [comment]
Please do download from http://www.ee.cuhk.edu.hk/~xgwang/CUHK_identification.html
