### ISSUE TITLE
Change the evaluation to a multi query shot

### ISSUE THREAD

**Issue by jpainam** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#14]
@hehefan
Can i use the same pretrained model for multi shot query setting or need to re write some part of your code.
Can you provide us with a mutli query evaluation example?

**Comment by hehefan** [comment]
Hi @jpainam, I do not intend to implement the multi-query evaluation code. You can find it in the page http://www.liangzheng.com.cn/Project/project_reid.html
