### ISSUE TITLE
Request for WHOS feature of DukeMTMC

### ISSUE THREAD

**Issue by ahangchen** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#15]
I'm working on Person reid and want to recurrent UMDL(a paper in CVPR2016, which used WHOS feature) on DukeMTMC-reID dataset. I found this newly published dataset hasn't been collected in Whos github project. Meanwhile, UMDL didn't conduct experiments on DukeMTMC-reID dataset.

But I found transfer result of UMDL in this work. I guess you have implemented UMDL on DukeMTMC and if so, you have WHOS feature for DukeMTMC.

Therefore, can you kindly release WHOS feature in this DukeMTMC-reID repository?

**Comment by hehefan** [comment]
Hi, we did not use the WHOS feature. As we mentioned in the paper, "Since the released code of UMDL
does not include feature extraction, we use the BoW feature proposed in [2] for this method."
