### ISSUE TITLE
ValueError: No such layer: avg_pool

### ISSUE THREAD

**Issue by mod1998** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#17]
I  run the  train.py  and get 0.ckpt,but when I use it to run unsupervised.py,I get the error:
Traceback (most recent call last):
  File "unsupervised.py", line 97, in <module>
    net = Model(input=previous_model.input, output=previous_model.get_layer('avg_pool').output)
  File "/home/zhangkun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/engine/network.py", line 364, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: avg_pool

**Comment by mod1998** [comment]
but I use your duke.ckpt to run unsupervised,there is no error.

**Comment by hehefan** [comment]
I think it may be caused by the keras version.
I use the version 2.0.4.　
You can also train a baseline model by yourself. It won't take too much time.
