### ISSUE TITLE
No Average Pooling Layer in the Model

### ISSUE THREAD

**Issue by naziaperwaiz** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#18]
Traceback (most recent call last):
  File "evaluate.py", line 71, in <module>
    net = Model(input=net.input, output=net.get_layer('avg_pool').output)
  File "/home/pc1/unsuper/local/lib/python2.7/site-packages/keras/engine/network.py", line 364, in get_layer
    raise ValueError('No such layer: ' + name)
ValueError: No such layer: avg_pool

@hehefan I have executed your base-line code and its giving the above mentioned error. Please assist as soon as possible.

**Comment by hehefan** [comment]
I think it may be caused by the keras version. 
I use the version 2.0.4.　
You can also train a baseline model by yourself. It won't take too much time.
