### ISSUE TITLE
avg_pol not exists in train.py?

### ISSUE THREAD

**Issue by mgq1507** [hehefan/Unsupervised-Person-Re-identification-Clustering-and-Fine-tuning#19]
why evluate.py has model.get_layer('avg_pol')?
keras version problem?
Hope you can reply me Thank you.

**Comment by hehefan** [comment]
Hi@mgq1507, it's a problem about the keras version.

**Comment by hehefan** [comment]
I think it may be caused by the keras version.
I use the version 2.0.4.　
You can also train a baseline model by yourself. It won't take too much time.
